name: Cypress Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  dev-deploy:
    uses: ./.github/workflows/_dev_deploy.yml
    secrets: inherit
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn run cypress
          browser: chrome
          headless: true
          record: true
